env: local
host: 0.0.0.0
port: 8001
redis:
  host: 127.0.0.1
oauth:
  clientId: oauth-third-party
  clientSecret: oauth-third-party
  callbackUrl: http://127.0.0.1:8001/home
  serverUrl: http://127.0.0.1:9000